#pragma once

#define APP_SYSTEM_CLOCK_FREQUENCY 16000000UL
#define APP_AHB_FREQUENCY          APP_SYSTEM_CLOCK_FREQUENCY
#define APP_APB1_FREQUENCY         (APP_SYSTEM_CLOCK_FREQUENCY / 2)
#define APP_APB2_FREQUENCY         APP_SYSTEM_CLOCK_FREQUENCY
#define APP_SYSTICK_FREQUENCY      1000000UL

