#pragma once

// Clock configuration
#define APP_SYSTEM_CLOCK_FREQUENCY 16000000UL
#define APP_AHB_FREQUENCY          APP_SYSTEM_CLOCK_FREQUENCY
#define APP_APB1_FREQUENCY         (APP_SYSTEM_CLOCK_FREQUENCY / 2)
#define APP_APB2_FREQUENCY         APP_SYSTEM_CLOCK_FREQUENCY
#define APP_SYSTICK_FREQUENCY      1000000UL

// FreeRTOS task memory configuration
#define TASK_MEM_DOMAIN_DUMP          128
#define TASK_MEM_IMMEDIATE_STOP       64
#define TASK_MEM_MANUAL_DISPATCH      64
#define TASK_MEM_MANUAL_MODE_SWITCH   64
#define TASK_MEM_MANUAL_MOTION        64
#define TASK_MEM_MANUAL_PID_TUNE      64
#define TASK_MEM_ROUTE_GUARD_TOGGLE   64
#define TASK_MEM_SHELL_COMMAND        64
#define TASK_MEM_SHELL_OUTPUT         128
#define TASK_MEM_TRACKING_DISPATCH    80
#define TASK_MEM_TRACKING_MODE_SWITCH 64
#define TASK_MEM_TRACKING_MOTION      64
#define TASK_MEM_USAGE_DUMP           128
